services:
  - type: web
    name: credits-tracking
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    startCommand: python3 -m http.server "$PORT" --directory /app
    autoDeploy: true
